apiVersion: v1
kind: Service
metadata:
  name: cozserver
  namespace: default
spec:
  selector:
    app: cozserver
  type: LoadBalancer
  ports:
  - name: cozserver
    protocol: TCP
    port: 8055
    targetPort: 8080

